services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
    restart: unless-stopped # Restart policy to ensure the container stays up
